from os import environ
from dotenv import load_dotenv

load_dotenv()

SQLALCHEMY_DATABASE_URI = environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = environ.get('SQLALCHEMY_TRACK_MODIFICATIONS')
SECRET_KEY = environ.get('SECRET_KEY')
FACEBOOK_OAUTH_CLIENT_ID = environ.get('FACEBOOK_OAUTH_CLIENT_ID')
FACEBOOK_OAUTH_CLIENT_SECRET = environ.get('FACEBOOK_OAUTH_CLIENT_SECRET')

# SECRET_KEY = b'4<W=7\x82\xc02\x91\xa1Xj^Eb\x04'
# SQLALCHEMY_DATABASE_URI = "sqlite:///app.sqlite3"
# SQLALCHEMY_TRACK_MODIFICATIONS = False
# FACEBOOK_OAUTH_CLIENT_ID = "289175938761351"
# FACEBOOK_OAUTH_CLIENT_SECRET = "55c2097ffd8d9684eead7278f8265d12"
